import fs from 'node:fs/promises';
import path from 'node:path';
import {Presentation,PresentationFile} from '@oai/artifact-tool';
const ROOT='/Users/namai/Documents/Project/HackMIT';
const B=path.join(ROOT,'presentation/.revision-v2');const A=path.join(ROOT,'presentation/revised/assets');
const C={bg:'#F3EFE6',ink:'#191A18',muted:'#5A5D59',blue:'#326B8C',gold:'#9B712B',red:'#AC493B',green:'#36705C',line:'#D6D2C7',soft:'#E4EBEB'};
const p=Presentation.create({slideSize:{width:1920,height:1080}});
const V=path.join(ROOT,'presentation/revised-v2/assets');
const F='Poppins';
function text(s,t,x,y,w,h,size=42,color=C.ink,bold=false,align='left',name){const o=s.shapes.add({geometry:'textbox',name:name||t.slice(0,50),position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});o.text=t;o.text.style={typeface:F,fontSize:size,color,bold,alignment:align,verticalAlignment:'top',autoFit:'none',insets:{left:0,right:0,top:0,bottom:0}};return o;}
function shape(s,x,y,w,h,fill,line='none',geometry='rect',name='diagram'){return s.shapes.add({geometry,name,position:{left:x,top:y,width:w,height:h},fill,line:{fill:line,width:line==='none'?0:2}});}
function line(s,x,y,w,color=C.line,width=2){return shape(s,x,y,w,width,color);}
function slide(title,sub='',notes=''){const s=p.slides.add();s.background.fill=C.bg;if(title)text(s,title,105,78,1710,130,72,C.ink,true);if(sub)text(s,sub,110,213,1700,105,35,C.muted);s.speakerNotes.textFrame.setText(notes);return s;}
async function img(s,file,x,y,w,h,fit='contain',crop){return s.images.add({blob:new Uint8Array(await fs.readFile(file)),contentType:file.endsWith('.svg')?'image/svg+xml':'image/png',fit,position:{left:x,top:y,width:w,height:h},...(crop?{crop}:{}),alt:path.basename(file)});}
function note(s,t){text(s,t,110,996,1690,50,25,C.muted);}
function connect(s,a,b,color=C.gold){return s.shapes.connect(a,b,{kind:'straight',fromSide:'right',toSide:'left',line:{fill:color,width:4},tail:{type:'triangle',width:'med',length:'med'}});}
function flow(s,items,y=430){const n=items.length;const gap=75;const w=(1700-gap*(n-1))/n;let prev;items.forEach((it,i)=>{const x=110+i*(w+gap);const box=shape(s,x,y,w,170,'none');text(s,it[0],x,y,w,90,43,it[2]||C.ink,true);text(s,it[1],x,y+96,w,180,31,C.muted);if(prev)connect(s,prev,box);prev=box;});}
function bar(s,{x=110,y=330,w=1700,h=540,categories,values,name,max,format='0.0',color=C.blue,points,labels=true}){const ch=s.charts.add('bar',{position:{left:x,top:y,width:w,height:h},categories,title:name,titleTextStyle:{typeface:F,fontSize:28,fill:C.muted},series:[{name,values,fill:color,points,valuesFormatCode:format,dataLabelOverrides:values.map((v,idx)=>({idx,text:v.toFixed(format==='0.000'?3:1),showValue:false,textStyle:{typeface:F,fontSize:36,fill:C.ink,bold:true}}))}],barOptions:{direction:'column',grouping:'clustered',gapWidth:140},hasLegend:false,chartFill:C.bg,plotAreaFill:C.bg,chartLine:{fill:'none'},plotAreaLine:{fill:'none'},xAxis:{textStyle:{typeface:F,fontSize:32,fill:C.ink},line:{fill:C.line,width:1},majorGridlines:null},yAxis:{min:0,max,numberFormatCode:format,textStyle:{typeface:F,fontSize:25,fill:C.muted},majorGridlines:{fill:C.line,width:1}},dataLabels:{showValue:labels,position:'outEnd',textStyle:{typeface:F,fontSize:36,fill:C.ink,bold:true}}});return ch;}
// 1 — user-selected connected lettering.
let s=slide('', '', 'Memorypalace. Revisit the moments you almost forgot. A personal memory companion that links changes in EEG activity with recorded context. Begin the 36-second film on the next slide.');
await img(s,path.join(ROOT,'design/branding/variants/01-clean.png'),0,0,1920,1080,'contain');
text(s,'Revisit the moments you almost forgot.',160,725,1600,110,52,C.ink,false,'center');text(s,'HackMIT 2026',160,907,1600,60,30,C.gold,false,'center');
// Opening question, before the film.
s=slide('', '', 'Open with an everyday lapse in recall, not a medical claim. This is a relatable motivation, not evidence that an EEG detector identifies forgetting. Transition to the concept film.');
text(s,'Ever walked into a room…',110,230,1650,145,90,C.ink,true);
text(s,'and forgotten what you came to say?',110,408,1660,210,82,C.ink,true);
text(s,'Our objective',110,731,1650,65,39,C.gold,true);text(s,'Revisit recorded moments, reflect on your day,\nand share selected experiences with someone close.',110,805,1660,160,39,C.blue);
// 2 — full-canvas embedded film; no duration / play-with-sound banner.
s=slide('', '', 'Play the embedded 36-second concept film with sound. It illustrates the intended wearable experience, using the approved mannequin and revised desk reaction. The neural strengths shown in the film are illustrative story values. The running prototype uses the phone camera and supports synthetic EEG replay plus a Crown adapter.');await img(s,path.join(A,'film-poster.png'),0,0,1920,1080,'cover');
// Reflection follows the film.
s=slide('Come back to your day','Revisit what happened. Learn from it. Let someone close understand.','At the end of the day, revisit selected recordings and their context. Reflection is a user activity, not a clinical assessment. The implemented Share flow drafts a personal note from selected moments; the user chooses the recipient, reviews the draft and shares it. Do not assert end-to-end encryption or a privacy guarantee that is not implemented. Source: app/components/share/SharePage.tsx.');
await img(s,path.join(A,'share.png'),110,345,1020,575);
text(s,'Reflect',1210,350,590,70,46,C.blue,true);text(s,'What happened?\nWhat do I want to learn?',1210,432,580,105,34,C.muted);
text(s,'Share with someone close',1210,608,600,115,44,C.ink,true);text(s,'Help them understand what\nstayed with you.',1210,722,590,110,33,C.muted);
text(s,'Deeply personal context. You choose what to share.',110,970,1690,75,37,C.gold,true);
// 4 — product concept and compact onboarding target.
s=slide('A personal memory companion','EEG identifies a change. Recorded context makes it useful.','Hardware concept: Neurosity Crown for sensing EEG and Ray-Ban Meta glasses for first-person context, supported by the Memorypalace app. Crown is an EEG sensor, not a neurostimulation device; Ray-Ban Meta glasses are not Meta Quest. The current working recorder is an Android phone camera, with a Crown stream adapter. Twenty minutes is the requested onboarding target, not a measured result; code baseline currently uses 120 seconds. Sources: hardware-demo/eegdemo/pipeline.py; hardware-demo/README.md; https://neurosity.co/crown ; https://wearables.developer.meta.com/docs/develop/dat/build-integration-android/');
await img(s,path.join(V,'crown.png'),110,350,730,515);
text(s,'Neurosity Crown',150,888,650,70,40,C.ink,true,'center');
text(s,'Sense',980,365,750,65,43,C.blue,true);text(s,'EEG compared with your personal baseline',980,433,800,82,32,C.muted);
text(s,'Capture context',980,554,750,65,43,C.gold,true);text(s,'Ray-Ban Meta glasses: the wearable camera concept',980,623,800,88,32,C.muted);
text(s,'Revisit',980,753,750,65,43,C.ink,true);text(s,'Search, reflect, and share in Memorypalace',980,822,800,88,32,C.muted);
// 5 — actual signal implementation, not an invented phase detector.
s=slide('Two checks before a moment is flagged','A change from your baseline, followed by a sustained elevation.','Current implementation: clean frontal EEG, theta (4–8 Hz) over alpha (8–13 Hz) band power, four-second non-overlapping windows, per-wearer z-score, threshold 2.0, four consecutive elevated windows. It measures a sustained load proxy. Phase-shift detection is not present in the inspected implementation; avoid describing this method as phase-shift inference or as a state-of-the-art benchmark. Source: confusion-detector/src/config.py; confusion-detector/src/cognitive_load.py; hardware-demo/eegdemo/pipeline.py.');
text(s,'01',110,380,220,140,96,C.blue,true);text(s,'Change from your normal',350,392,1400,100,58,C.ink,true);text(s,'Compare theta/alpha activity with your own resting baseline.',350,520,1360,130,40,C.muted);
line(s,110,689,1695);text(s,'02',110,754,220,140,96,C.gold,true);text(s,'Sustained burst confirmation',350,765,1400,95,58,C.ink,true);text(s,'Keep the event only after four fresh windows stay elevated.',350,880,1360,100,40,C.muted);
// Three wearers: raw range is an illustration; theta/alpha remains the implemented trigger.
s=slide('Start by learning your normal','First-time calibration gives each wearer a personal reference.','The three raw EEG traces and 20 / 40 / 70 microvolt ranges are synthetic illustrations, not measured people or diagnostic norms. Peak-to-peak means maximum minus minimum; raw amplitude also depends on recording conditions. The live prototype calibrates theta/alpha mean and spread over 120 seconds, then uses a z-score. It does not trigger from raw peak-to-peak amplitude. Person icon: Lucide user-round, https://github.com/lucide-icons/lucide/blob/main/icons/user-round.svg (ISC).');
for(let i=0;i<3;i++){
 const x=110+i*570, amp=[10,20,35][i],col=[C.blue,C.gold,C.green][i];
 const raw=Array.from({length:65},(_,j)=>Math.sin(j*.77)+.3*Math.sin(j*2.13));const lo=Math.min(...raw),hi=Math.max(...raw);const values=raw.map(v=>Number((((v-lo)/(hi-lo)*2-1)*amp).toFixed(1)));
 s.charts.add('line',{position:{left:x,top:335,width:535,height:280},categories:values.map((_,j)=>String(j)),title:'Wearer '+String.fromCharCode(65+i),titleTextStyle:{typeface:F,fontSize:33,fill:col,bold:true},series:[{name:'Illustrative raw EEG (µV)',values,line:{fill:col,width:3},marker:{symbol:'none'},valuesFormatCode:'0.0'}],hasLegend:false,chartFill:C.bg,plotAreaFill:C.bg,lineOptions:{smooth:false},xAxis:{visible:false,tickLabelPosition:'none',line:{fill:'none'},textStyle:{typeface:F,fontSize:20,fill:C.muted}},yAxis:{min:-40,max:40,numberFormatCode:'0',textStyle:{typeface:F,fontSize:20,fill:C.muted},majorGridlines:{fill:C.line,width:1}},chartLine:{fill:'none'},plotAreaLine:{fill:'none'}});
 await img(s,path.join(V,'person.png'),x+175,643,185,185);
 text(s,[20,40,70][i]+' µV peak-to-peak',x,849,535,60,35,col,true,'center');
}
text(s,'Different ranges. A baseline that belongs to you.',110,947,1700,65,40,C.ink,true);
note(s,'Illustrative raw EEG • peak-to-peak = highest minus lowest • trigger uses normalized theta/alpha activity');
// 6 — native editable chart; a short staged explanation is added as video.
function baseline(deck,stage=2){const sl=deck.slides.add();sl.background.fill=C.bg;text(sl,'Your baseline makes the signal meaningful',105,78,1710,130,72,C.ink,true);text(sl,'The same reading can be unusual for one person and normal for another.',110,213,1700,100,35,C.muted);
if(stage===0){text(sl,'Same reading',110,400,800,90,52,C.ink,true);text(sl,'3.0',112,512,900,240,170,C.blue,true);text(sl,'Different resting patterns',1010,415,760,110,46,C.ink,true);text(sl,'Wearer A: usually around 1.0\nWearer B: usually around 2.6',1010,570,780,220,39,C.muted);}else{bar(sl,{x:130,y:340,w:1120,h:535,categories:['Wearer A','Wearer B'],values:[4,.8],name:'Change from personal baseline (standard deviations)',max:5,points:[{idx:0,fill:C.gold},{idx:1,fill:C.blue}]});text(sl,'Same raw value.\nDifferent meaning.',1325,410,470,160,48,C.ink,true);if(stage===2){text(sl,'A: unusual change',1325,644,480,70,36,C.gold,true);text(sl,'B: within usual range',1325,750,480,100,36,C.blue,true);}}note(sl,'Illustrative example • the current baseline routine collects 120 seconds of EEG');sl.speakerNotes.textFrame.setText('Illustrative arithmetic: raw theta/alpha index 3.0; A mean 1.0 and standard deviation 0.5 gives z=4.0; B mean 2.6 and standard deviation 0.5 gives z=0.8. These are explanatory values, not measured people or clinical thresholds. The implemented trigger threshold is z=2.0. Source: confusion-detector/src/detector.py and config.py. The chart remains editable beneath its animated video overlay.');return sl;}
s=baseline(p,2);
// 7 — four fresh windows. No statistical independence claim.
function persistence(deck,stage=4){const sl=deck.slides.add();sl.background.fill=C.bg;text(sl,'Four fresh windows confirm one event',105,78,1710,130,72,C.ink,true);text(sl,'Each window uses new EEG samples. A dip below the threshold resets the count.',110,213,1700,100,35,C.muted);const items=[];for(let i=0;i<4;i++){const x=110+i*425,active=i<stage;const sh=shape(sl,x,420,370,220,active?C.blue:'#E2E3DF');text(sl,`${i*4}–${(i+1)*4} s`,x+18,456,334,80,56,active?'#FFFFFF':C.muted,true,'center');text(sl,active?'Elevated':'Next window',x+18,553,334,60,32,active?'#FFFFFF':C.muted,false,'center');items.push(sh);if(i>0)connect(sl,items[i-1],sh,C.gold);}text(sl,`${stage} / 4 confirmed`,110,735,1300,100,65,C.ink,true);if(stage===4)text(sl,'Flag the moment',110,862,1450,90,59,C.gold,true);else text(sl,'Wait for sustained evidence',110,862,1450,90,48,C.muted);note(sl,'Current detector: 4-second non-overlapping windows • illustrative signal sequence');sl.speakerNotes.textFrame.setText('Four consecutive windows above z=2.0 are required. No overlap means samples are not reused; it does not prove statistical independence of brain activity. The active backend finalizes an ongoing recording on this trigger, attaches the signal context, and saves it. The concept film illustrates the broader event-capture vision. Sources: confusion-detector/src/config.py; hardware-demo/eegdemo/server.py Runtime.trigger.');return sl;}
s=persistence(p,4);
// 8 — controlled, measured comparison with explicit scope.
s=slide('Fresh samples reduced false alarms','Changing the overlap changed the result—even with the same threshold.','Controlled comparison reported in confusion-detector/README.md, The one result that matters: 4-second windows, 75% overlap (hop 1s) 30.3 false alarms/hour; 50% overlap (hop 2s) 18.9; no overlap (hop 4s) 1.3. Same stationary synthetic fixture and threshold. Do not generalize the absolute rate to people or drifting baselines; the drifting fixture reported 7.2/hour at the default setting. This chart is engineering evidence for avoiding repeated samples, not a clinical performance claim.');bar(s,{categories:['75% overlap','50% overlap','No overlap'],values:[30.3,18.9,1.3],name:'False alarms per hour',max:35,points:[{idx:0,fill:C.red},{idx:1,fill:C.gold},{idx:2,fill:C.blue}]});note(s,'Controlled synthetic fixture • same data and threshold • source: confusion-detector/README.md');
// 9 — actual running retrieval UI, plus a clickable demo link.
s=slide('Find the moment again','Search what you remember. Open the original clip.','Live demo at http://localhost:3000/explore. Query: laptop keyboard. The screenshot is captured from the running project, not a fabricated interface. Elastic combines keyword and vector retrieval, with timeline and intensity filters. Sources: app/components/explore; hardware-demo/eegdemo/elastic_store.py. Keep the standalone app running when using the demo link.');await img(s,path.join(A,'search-keyboard.png'),110,335,1290,680,'contain');text(s,'“laptop keyboard”',1450,405,370,135,41,C.blue,true);text(s,'Search by a detail\nyou still remember.',1450,605,360,165,35,C.muted);let link=text(s,'Open live demo →',1450,900,375,90,32,C.ink,true);link.text=[[{run:'Open live demo →',link:{uri:'http://localhost:3000/explore',isExternal:true}}]];link.text.style={typeface:F,fontSize:32,color:C.blue,bold:true};
// 10 — Elastic track, response to prompt and implementation.
s=slide('Elastic for memory search','Sponsor challenge: turn messy data into insights, answers or actions.','Challenge source: DOCS_sponsor/elastic. Implementation: Elastic Cloud Serverless, Jina v5 Omni via Elastic Inference, semantic metadata, BM25 + dense kNN with RRF, date and EEG-intensity filters. The persisted video is linked from the retrieved moment. Sources: hardware-demo/eegdemo/elastic_store.py; FULFILLMENT_SPONSORS.md. Logo source: https://www.apmdigest.com/sites/default/files/2024-09/logo_elastic.png ; brand owner https://www.elastic.co/ . Official method references: https://www.elastic.co/docs/solutions/search/multimodal-search ; https://www.elastic.co/docs/reference/elasticsearch/rest-apis/reciprocal-rank-fusion .');await img(s,path.join(A,'elastic-color.png'),1370,65,410,135);flow(s,[['Recorded moment','Video + time + EEG context',C.ink],['Jina v5 Omni','A shared space for clips\nand search questions',C.blue],['Hybrid search','Keywords + meaning\nBM25 + kNN → RRF',C.gold]],430);text(s,'A question becomes a replayable memory.',110,824,1620,105,55,C.ink,true);note(s,'Implemented with Elastic Cloud Serverless and Elastic Inference Service');
// Meta models mapped to actual app features.
s=slide('Meta connects your moments','Understand a moment, ask about it, then share what matters.','Sponsor prompt: Bringing People Closer Together with AI. Muse Spark (muse-spark-1.3) is used in vision.py for recorded-video descriptions and in agent.py for Memory Guard reasoning/tool use and share_note generation. Muse Voice Transcribe (muse-voice-transcribe-1.0) transcribes push-to-talk input in voice.py; playback speech uses device speech synthesis. Muse Image and a Muse personal-agent connector are not implemented and are not claimed. Sources: hardware-demo/eegdemo/vision.py; agent.py; voice.py; app/components/share/SharePage.tsx. Sponsor links: https://developer.meta.com/ai/models/muse-spark/ and https://developer.meta.com/ai/models/muse-voice-transcribe/ .');
await img(s,path.join(A,'meta.png'),1430,70,350,125,'contain',{left:0,top:.26,right:0,bottom:.26});
const metaRows=[['Describe the moment','Muse Spark','Turns a recorded clip into a searchable description.'],['Talk to Memory Guard','Muse Voice Transcribe + Muse Spark','Transcribes your question, then reasons over retrieved moments.'],['Share with someone close','Muse Spark','Drafts a personal note from moments you select and review.']];
for(let i=0;i<3;i++){const y=350+i*210;text(s,metaRows[i][0],110,y,660,70,40,C.ink,true);text(s,metaRows[i][1],825,y,940,62,35,C.blue,true);text(s,metaRows[i][2],825,y+73,945,102,31,C.muted);if(i<2)line(s,110,y+181,1690);}
text(s,'Personal context becomes a way to connect.',110,993,1670,55,34,C.gold,true);
// VoloRidge approach and validation, from SLIDES-VOLORIDGE.md.
s=slide('84 numbers and a logistic regression','Voloridge • extracting sustained state changes from public EEG data','Voloridge asked for signal out of public data. Ours is EEG: 28 channels, five people, fifteen sessions from Shin et al. 2018 dataset A. Regress out eye-channel contributions, measure three band powers, logistic regression, one moving average. Alternatives were paired against their own baselines on the same recordings, windows and calibration folds. They lost or tied; these rows are not a cross-participant leaderboard. The one retained addition is a smoothing half-life. Source: presentation/SLIDES-VOLORIDGE.md and eeg-state-detection/README.md. Public-data research, distinct from the running four-window prototype detector.');
shape(s,1570,40,240,160,'#102F45');await img(s,path.join(A,'voloridge.png'),1580,43,220,150);
text(s,'The pipeline',110,339,740,65,42,C.blue,true);
const steps=[['28 EEG channels, 200 Hz','Shin et al. 2018 • five people, 15 sessions'],['Regress out eye channels','Fit before task; freeze before scoring'],['Theta / alpha / beta log power','84 features • 2-second windows, every 0.25 s'],['Logistic regression → moving average','Task versus rest • one smoothing parameter']];
for(let i=0;i<4;i++){let y=432+i*138;text(s,steps[i][0],110,y,830,62,34,C.ink,true);text(s,steps[i][1],110,y+57,830,66,28,C.muted);}
text(s,'More complexity did not win',1010,339,800,70,41,C.ink,true);
for(const [i,label,count] of [[0,'Riemannian tangent space','1,218 features'],[1,'26-bin Fourier spectrum','728 features'],[2,'Zigzag topology','108 features'],[3,'Bayesian state-space','Latent state'],[4,'Three more alternatives','Lost or tied']]){let y=435+i*73;text(s,label,1010,y,480,62,28,C.muted);text(s,count,1515,y,290,62,27,C.muted);}
line(s,1010,827,790,C.gold,3);text(s,'Band power + logistic',1010,858,785,67,40,C.ink,true);text(s,'84 features + one smoothing parameter',1010,931,790,68,30,C.gold,true);
note(s,'Paired comparisons against each method’s own baseline • source: eeg-state-detection/README.md');
s=slide('Does the signal survive a harder test?','Voloridge • models frozen before scoring held-out task blocks','Models were frozen and SHA-256 hashed before held-out blocks. Per session: first six blocks calibrate, last three score. The circular time-shift null preserves autocorrelation; shuffled windows would break it. 2,000 shifts per session. Eight of 15 sessions beat that null at nominal p ≤ 0.05 (session-wise, not multiplicity corrected). Orange diamonds are the identical pipeline on eye channels; two participants show substantial ocular contribution. The same null discipline rejected the brief-event zigzag result: 6/36 versus a 2/36 baseline, p=0.13 against random flags. Sources: eeg-state-detection/README.md; outputs/backtest_state/report.json; outputs/burst_diagnostic_dev/report.json. This is offline task/rest detection, not real-world forgetting or emotion accuracy.');
shape(s,1570,40,240,160,'#102F45');await img(s,path.join(A,'voloridge.png'),1580,43,220,150);
await img(s,path.join(ROOT,'eeg-state-detection/outputs/backtest_state/summary.png'),85,315,1750,595,'contain');
text(s,'Grey: random alignment of the same signal. 8 of 15 sessions beat it at p ≤ 0.05.',110,927,1690,65,29,C.ink,true);
line(s,110,1005,1690,C.gold,2);text(s,'Brief-event detector: 3× its baseline, but p = 0.13 against random flags — rejected.',110,1021,1700,45,25,C.gold,true);
// 13 — requested architecture, native editable topology.
s=slide('System architecture','A signal and its recorded context become one searchable moment.','Actual wiring: Crown publisher sends EEG to Python backend. Android camera client polls authenticated commands and uploads video to the backend. Backend persists the catalog, calls Meta enrichment and Elastic indexing. Next.js browser accesses backend through server routes. Source: hardware-demo/eegdemo/server.py; pipeline.py; library.py; elastic_store.py; app/lib/backend.ts. The native diagram is editable.');
const nodes={};function node(k,title,desc,x,y,w=420,h=170,color=C.ink){let q=shape(s,x,y,w,h,'none');text(s,title,x,y,w,65,44,color,true);text(s,desc,x,y+82,w,h-70,29,C.muted);nodes[k]=q;return q;}
node('eeg','Crown EEG','Signal packets',110,410,380,170,C.blue);node('camera','Camera client','Video + capture commands',110,750,420,170,C.gold);node('backend','Python backend','Detect • finalize • store',680,565,510,175);node('meta','Meta','Describe the moment',1390,360,400,160,C.blue);node('elastic','Elastic','Index + retrieve',1390,610,400,160,C.gold);node('web','Web app','Search • replay • share',1390,854,430,150);
s.shapes.connect(nodes.eeg,nodes.backend,{kind:'elbow',fromSide:'right',toSide:'left',line:{fill:C.blue,width:3},tail:{type:'triangle'}});s.shapes.connect(nodes.camera,nodes.backend,{kind:'elbow',fromSide:'right',toSide:'left',line:{fill:C.gold,width:3},head:{type:'triangle'},tail:{type:'triangle'}});for(const key of ['meta','elastic','web'])s.shapes.connect(nodes.backend,nodes[key],{kind:'elbow',fromSide:'right',toSide:'left',line:{fill:C.muted,width:3},head:{type:'triangle'},tail:{type:'triangle'}});
// 14 — confident close, no defensive checklist.
s=slide('', '', 'Close: Memorypalace turns a fleeting reaction into a moment you can revisit, understand, and choose to share. Invite the judges to try the running retrieval demo. The film describes the wearable concept; the charts and sponsor slides show the implemented work.');text(s,'Memorypalace',110,198,1700,150,116,C.ink,true);text(s,'Your day has more to tell you.',110,436,1610,220,90,C.ink,true);text(s,'Keep the context. Revisit it when you have time.',110,754,1640,135,47,C.blue);let q=text(s,'Try the live demo →',110,937,1100,65,34,C.gold,true);q.text=[[{run:'Try the live demo →',link:{uri:'http://localhost:3000/',isExternal:true}}]];q.text.style={typeface:F,fontSize:34,color:C.gold,bold:true};
await fs.mkdir(path.join(B,'previews'),{recursive:true});
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(B,'previews',`${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));console.log('RENDERED',i+1);}
await (await PresentationFile.exportPptx(p)).save(path.join(B,'candidate-base.pptx'));
console.log('DECK READY');
