#!/usr/bin/env python3
"""Turn real EPOC X recordings into a loopable replay buffer for the web monitor.

The live monitor used to draw two summed sine waves per channel, which reads as a
cartoon of EEG: no 1/f slope, no drift, no blinks, identical rhythm on every channel.
This builds a short continuous trace out of the team's own EPOC X session instead, so
the waveform on screen has real spectral content and real artifacts.

The output is deliberately small and committed: 30 s, 8 channels, int16, base64 in a
TypeScript module, so the web app needs no fetch, no binary asset and no network.

Run:  confusion-detector/.venv/bin/python scripts/build_eeg_replay.py
"""
import base64
import csv
import glob
import json
from pathlib import Path

import numpy as np
from scipy.signal import butter, filtfilt, iirnotch

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "dataset" / "epocx-imagery" / "extracted"
OUT = ROOT / "app" / "lib" / "eegReplay.ts"

# EPOC X records 14 channels. These 8 are the frontal and lateral sites closest to the
# montage the detector targets, and they are the ones carrying the frontal activity the
# spike detector keys on.
CHANNELS = ["AF3", "F7", "F3", "FC5", "FC6", "F4", "F8", "AF4"]
FS = 128.0           # EPOC X sample rate
SECONDS = 30.0
TARGET_UV_STD = 14.0  # realistic scalp EEG amplitude after referencing


def load_trial(path):
    """Some exports carry a metadata preamble line before the real header."""
    with open(path) as fh:
        rows = list(csv.reader(fh))
    start = 1 if rows[0] and rows[0][0].startswith("title:") else 0
    header = rows[start]
    idx = [header.index(f"EEG.{c}") for c in CHANNELS]
    body = rows[start + 1:]
    data = np.array([[float(r[i]) for i in idx] for r in body if r[idx[0]] != ""],
                    dtype=np.float64)
    return data.T  # (channels, samples)


def main():
    files = sorted(p for p in glob.glob(str(SOURCE / "*" / "*bp.csv"))
                   if "intervalMarker" not in p)
    if not files:
        raise SystemExit(f"no trials found under {SOURCE}")

    need = int(FS * SECONDS)
    chunks, used = [], []
    for path in files:
        try:
            trial = load_trial(path)
        except Exception:
            continue
        if trial.shape[1] < int(FS * 4):
            continue
        # Drop the first and last second: the recording edges hold setup transients.
        trial = trial[:, int(FS):-int(FS)]
        if trial.shape[1] < int(FS * 2):
            continue
        chunks.append(trial)
        used.append(Path(path).name)
        if sum(c.shape[1] for c in chunks) >= need + int(FS * 4):
            break

    raw = np.concatenate(chunks, axis=1)[:, :need + int(FS * 2)]

    # EPOC X reports around 4300 uV of DC offset per channel. Remove the offset and the
    # slow drift, keep 1-40 Hz, and notch mains so the trace is not dominated by it.
    b, a = butter(4, [1.0 / (FS / 2), 40.0 / (FS / 2)], btype="band")
    clean = filtfilt(b, a, raw, axis=1)
    bn, an = iirnotch(50.0, 30.0, FS)
    clean = filtfilt(bn, an, clean, axis=1)

    # Common average reference, which is what makes separate channels look related
    # rather than independent, exactly as real scalp EEG does.
    clean = clean - clean.mean(axis=0, keepdims=True)
    # Keep one extra second past the loop point: the cross-fade below needs the samples
    # that would have followed the end, not the ones that precede it.
    fade = int(FS)
    clean = clean[:, int(FS):int(FS) + need + fade]

    # Scale to a realistic microvolt range, preserving the relative differences between
    # channels rather than normalising each one separately.
    scale = TARGET_UV_STD / float(np.median(clean.std(axis=1)))
    clean *= scale

    # Cross-fade so sample 0 continues smoothly from sample need-1 when the buffer wraps.
    # At i=0 the ramp is 0, so the first sample becomes exactly the one that followed the
    # loop point in the original recording, which is what makes the wrap invisible.
    ramp = np.linspace(0.0, 1.0, fade)
    clean[:, :fade] = clean[:, :fade] * ramp + clean[:, need:need + fade] * (1.0 - ramp)
    clean = clean[:, :need]

    ints = np.clip(np.round(clean * 8.0), -32768, 32767).astype("<i2")
    payload = base64.b64encode(ints.T.tobytes()).decode("ascii")

    OUT.write_text(
        "// Generated by scripts/build_eeg_replay.py. Do not edit by hand.\n"
        "//\n"
        "// A real 30 s, 8 channel EEG trace taken from the team's own Emotiv EPOC X\n"
        "// recordings in dataset/epocx-imagery, bandpassed 1-40 Hz, notched, common\n"
        "// average referenced and scaled to microvolts. Samples are int16 at 8 counts\n"
        "// per microvolt, interleaved by channel, so the browser reconstructs the trace\n"
        "// without a fetch. This is replayed recorded data, never live capture.\n"
        f"export const REPLAY_SAMPLE_RATE = {FS};\n"
        f"export const REPLAY_CHANNELS = {json.dumps(CHANNELS)};\n"
        f"export const REPLAY_SECONDS = {SECONDS};\n"
        "export const REPLAY_SCALE = 8;\n"
        f"export const REPLAY_SOURCE_TRIALS = {json.dumps(used[:6])};\n"
        f'export const REPLAY_BASE64 = "{payload}";\n',
    )
    kb = len(payload) / 1024
    print(f"channels        : {CHANNELS}")
    print(f"trials used     : {len(used)} ({', '.join(used[:3])} ...)")
    print(f"samples/channel : {clean.shape[1]} ({clean.shape[1]/FS:.1f}s at {FS} Hz)")
    print(f"amplitude uV    : std {clean.std():.1f}, p2p {np.ptp(clean):.0f}")
    print(f"written         : {OUT.relative_to(ROOT)}  ({kb:.0f} KB base64)")


if __name__ == "__main__":
    main()
